LANGUAGES = {
    "vi": {
        "upload_label": "📂 Tải lên file code hoặc ảnh chụp code",
        "select_mode": "🔍 Chọn chế độ Review",
        "run_btn": "🚀 Bắt đầu Review",
        "clear_btn": "🧹 Xóa Chat",
        "chat_placeholder": "Nhập câu hỏi về code hoặc lỗi...",
        "tab_review": "💬 Review Code",
        "tab_chat": "🧠 Trò chuyện cùng AI",
        "processing": "🚀 Đang phân tích code...",
        "no_review_yet": "📂 Hãy tải file và chọn chế độ để bắt đầu review.",
        "success_review": "✅ Review hoàn tất! Xem kết quả ở tab Review.",
        "choose_convention": "📘 Upload file Coding Convention (Excel)",
        "linter_output": "🧾 Kết quả phân tích cú pháp (Linter)",
        "detected_lang": "🧩 Phát hiện ngôn ngữ",
        "ocr_detected": "🧠 Đã nhận diện code từ ảnh",
        "rule_violation": "🚫 Vi phạm quy tắc",
        "severity": "Mức độ",
        "description": "Mô tả",
        "suggestion": "Gợi ý",
        "style_mode": "🧹 Style Checker (Convention)",
        "perf_mode": "⚙️ Performance Expert (Logic & Hiệu năng)",
        "requirement_suggestion": "📂 Upload file và chọn chế độ review để bắt đầu.",
        "enter_chat": "Nhập tin nhắn để hỏi AI...",
    },
    "en": {
        "upload_label": "📂 Upload a code file or code image",
        "select_mode": "🔍 Select Review Mode",
        "run_btn": "🚀 Start Review",
        "clear_btn": "🧹 Remove Chat",
        "chat_placeholder": "Ask something about the code or detected issues...",
        "tab_review": "💬 Code Review",
        "tab_chat": "🧠 Chat with AI",
        "processing": "🚀 Analyzing the code...",
        "no_review_yet": "📂 Please upload a file and select review mode to start.",
        "success_review": "✅ Review completed! Check the Review tab for results.",
        "choose_convention": "📘 Upload Coding Convention (Excel)",
        "linter_output": "🧾 Linter Output",
        "detected_lang": "🧩 Detected language",
        "ocr_detected": "🧠 Extracted code from image",
        "rule_violation": "🚫 Rule Violation",
        "severity": "Severity",
        "description": "Description",
        "suggestion": "Suggestion",
        "style_mode": "🧹 Style Checker (Convention)",
        "perf_mode": "⚙️ Performance Expert (Logic & Performance)",
        "requirement_suggestion": "📂 Upload file and choose review mode to start.",
        "enter_chat": "Enter something...",
    },
}
